services:
  web:
    build: .
    environment:
      - SECRET_KEY=your_production_or_dev_key
      - DEBUG=False
      - ALLOWED_HOSTS=*
    command: >
      sh -c "python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 ecommerce.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
