# k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
      tier: web
  template:
    metadata:
      labels:
        app: ecommerce
        tier: web
    spec:
      containers:
        - name: web
          image: your-registry/ecommerce:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ecommerce-secrets
            - configMapRef:
                name: ecommerce-config
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: regcred