# k8s/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  # Generate base64 encoded values (echo -n "value" | base64)
  SECRET_KEY: <base64-encoded-django-secret-key>
  DATABASE_URL: <base64-encoded-db-url>
  DB_NAME: <base64-encoded-db-name>
  DB_USER: <base64-encoded-db-user>
  DB_PASSWORD: <base64-encoded-db-password>
  AWS_ACCESS_KEY_ID: <base64-encoded-aws-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-aws-secret-key>
  EMAIL_HOST_USER: <base64-encoded-email-user>
  EMAIL_HOST_PASSWORD: <base64-encoded-email-password>
  AFRICASTALKING_API_KEY: <base64-encoded-api-key>