# k8s/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret>
  DATABASE_URL: <base64-encoded-db-url>
  EMAIL_HOST_PASSWORD: <base64-encoded-email-password>
  AFRICASTALKING_API_KEY: <base64-encoded-api-key>