# k8s/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  # Generate base64 encoded values (echo -n "value" | base64)
  SECRET_KEY: NUB3XzdiKS02KDUwd25rMzEjJDYpIyohKDZ4bzcjIylvYXglKmoxYjFzQG15OTgqazUhekA=
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpjb3NvbWElMjNGMSNkYjo1NDMyL2Vjb21tZXJjZQ==
  DB_NAME: ZWNvbW1lcmNl
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: Y29zb21hI0ox
  AWS_ACCESS_KEY_ID: QUtJQTRSRU5KU0lQQUlSR0RCUk8=
  AWS_SECRET_ACCESS_KEY: S3NETWhIV0hxYXQzV3lxUjFsNENERk9BcEQrNEdHZ1UwbVd2TE5SbQ==
  OIDC_CLIENT_ID: Q0pXcmhiSlJsakFxM3lDS093RkJGallYWXdNU1VXSjE=
  OIDC_CLIENT_SECRET: Yk92cVNyNWdXQ1NWRnA0dG1QMzhRTGVQUUVmNnF2M3l5djRucFhDWGJKVjdwZG96ZDZqRHBsSnNvVVBST1ZUeA==
  EMAIL_HOST_USER: amVmZm13bkBnbWFpbC5jb20=
  EMAIL_HOST_PASSWORD: YXl4cGtqeHFjaW1nZGxsZA==
  AFRICASTALKING_USERNAME: aW50ZWxpc2F2ZGV2
  AFRICASTALKING_API_KEY: YXRzak8wMDc0NTU3NjRmMTI3ZGUxODVjMDI0MmRiMTJjNDZlMGIwZTRmYzlmNDYwMjhjYjE3YmNjNGMwNDQ3NDIyMmYzMjc3NmNkMTA=


